### ISSUE TITLE
"Invalid GoRename parameters"

### ISSUE THREAD

**Issue by mkleina** [alvarolm/GoRename#5]
I have gorename tool installed, it works great it Atom editor. When I press Ctrl+Alt+R, ESC, then type new variable name and press Enter, console shows part of code and "Press ENTER to continue" message. After pressing Enter again, console shows "gorename: surplus arguments" message and "Invalid GoRename parameters" popup appears. Code is not modified after that, so plugin doesn't work at all for me. I am using Ubuntu 16.04 and Sublime Text 3 build 3103.

**Comment by alvarolm** [comment]
make sure that when yout type the new variable name there's no more than one word.

**Comment by alvarolm** [comment]
I wasn't able to reproduce this btw, please make sure you have the latest version.

**Comment by alvarolm** [comment]
its seems there is a some weird first time running behavior, after installation try restarting sublime.

**Comment by mkleina** [comment]
I restarted sublime several times, every time I'm typing single-word variable. Plugin was installed today from Package Control package manager. There are also some errors when I look into sublime console:
```
Package Control: Skipping automatic upgrade, last run at 2016-05-24 17:55:43, next run at 2016-05-24 18:55:43 or after
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
Unable to fetch update url contents
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
```

**Comment by mkleina** [comment]
I restarted sublime several times, every time I'm typing single-word variable. Plugin was installed today from Package Control package manager. There are also some errors when I look at sublime console:
```
Package Control: Skipping automatic upgrade, last run at 2016-05-24 17:55:43, next run at 2016-05-24 18:55:43 or after
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
Unable to fetch update url contents
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
```

**Comment by mkleina** [comment]
I restarted Sublime several times, every time I'm typing single-word variable. Plugin was installed today from Package Control package manager. There are also some errors when I look at Sublime console:

```
Package Control: Skipping automatic upgrade, last run at 2016-05-24 17:55:43, next run at 2016-05-24 18:55:43 or after
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
Unable to fetch update url contents
error: Invalid GoRename parameters
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 574, in run_
    return self.run(edit)
  File "goRename in /home/mkleina/.config/sublime-text-3/Installed Packages/GoRename.sublime-package", line 317, in run
KeyError: 'file_path'
```

**Comment by mkleina** [comment]
It is some problem with args passing to gorename tool for sure, but I can't see any logs what the plugin really trying to launch. To reproduce the same message just type in console:

```
$ gorename non-existing-argument
gorename: surplus arguments
```

This is my gorename --help output:

```
gorename: precise type-safe renaming of identifiers in Go source code.

Usage:

 gorename (-from <spec> | -offset <file>:#<byte-offset>) -to <name> [-force]

You must specify the object (named entity) to rename using the -offset
or -from flag.  Exactly one must be specified.

Flags:

-offset    specifies the filename and byte offset of an identifier to rename.
           This form is intended for use by text editors.

-from      specifies the object to rename using a query notation;
           This form is intended for interactive use at the command line.
           A legal -from query has one of the following forms:

  "encoding/json".Decoder.Decode        method of package-level named type
  (*"encoding/json".Decoder).Decode     ditto, alternative syntax
  "encoding/json".Decoder.buf           field of package-level named struct type
  "encoding/json".HTMLEscape            package member (const, func, var, type)
  "encoding/json".Decoder.Decode::x     local object x within a method
  "encoding/json".HTMLEscape::x         local object x within a function
  "encoding/json"::x                    object x anywhere within a package
  json.go::x                            object x within file json.go

           Double-quotes must be escaped when writing a shell command.
           Quotes may be omitted for single-segment import paths such as "fmt".

           For methods, the parens and '*' on the receiver type are both
           optional.

           It is an error if one of the ::x queries matches multiple
           objects.

-to        the new name.

-force     causes the renaming to proceed even if conflicts were reported.
           The resulting program may be ill-formed, or experience a change
           in behaviour.

           WARNING: this flag may even cause the renaming tool to crash.
           (In due course this bug will be fixed by moving certain
           analyses into the type-checker.)

-d         display diffs instead of rewriting files

-v         enables verbose logging.

gorename automatically computes the set of packages that might be
affected.  For a local renaming, this is just the package specified by
-from or -offset, but for a potentially exported name, gorename scans
the workspace ($GOROOT and $GOPATH).

gorename rejects renamings of concrete methods that would change the
assignability relation between types and interfaces.  If the interface
change was intentional, initiate the renaming at the interface method.

gorename rejects any renaming that would create a conflict at the point
of declaration, or a reference conflict (ambiguity or shadowing), or
anything else that could cause the resulting program not to compile.


Examples:

$ gorename -offset file.go:#123 -to foo

  Rename the object whose identifier is at byte offset 123 within file file.go.

$ gorename -from '"bytes".Buffer.Len' -to Size

  Rename the "Len" method of the *bytes.Buffer type to "Size".

---- TODO ----

Correctness:
- handle dot imports correctly
- document limitations (reflection, 'implements' algorithm).
- sketch a proof of exhaustiveness.

Features:
- support running on packages specified as *.go files on the command line
- support running on programs containing errors (loader.Config.AllowErrors)
- allow users to specify a scope other than "global" (to avoid being
  stuck by neglected packages in $GOPATH that don't build).
- support renaming the package clause (no object)
- support renaming an import path (no ident or object)
  (requires filesystem + SCM updates).
- detect and reject edits to autogenerated files (cgo, protobufs)
  and optionally $GOROOT packages.
- report all conflicts, or at least all qualitatively distinct ones.
  Sometimes we stop to avoid redundancy, but
  it may give a disproportionate sense of safety in -force mode.
- support renaming all instances of a pattern, e.g.
  all receiver vars of a given type,
  all local variables of a given type,
  all PkgNames for a given package.
- emit JSON output for other editors and tools.
```

**Comment by alvarolm** [comment]
the debug logs would be very useful, to enable them go to
Preferences > Package Settings > GoRename > Settings - User
and set gorename_debug to true then restart and copy paste the lines from the console that start with 'GoRename'

**Comment by mkleina** [comment]
Here you got:
```
GoRename [DEBUG]: ('flags:', '')
GoRename [DEBUG]: ('Stored rename parameters:', {'checksum': 'd617cc26242bbb30ef0331427c160bc755e70a695175e27f75957a147b30d115', 'file_path': '/home/mkleina/Link to intelsdi-x/snap-plugin-collector-cgroups/cgroups/cgroups.go', 'compiled_message': 'Running GoRename %s:\nFrom getFullNamespace to getBlablah\n[Line Number: 251][Byte Offset: 7066]\nFlags: []\nReference:\nfunc (mp *mountpoint) getFullNamespace(mountpoint string, metric string) (result core.Namespace) {', 'offset': 7066, 'name': 'getBlablah', 'flags': ''})
GoRename [DEBUG]: ('env', {'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'SHLVL': '1', 'UPSTART_EVENTS': 'xsession started', 'LC_IDENTIFICATION': 'pl_PL.UTF-8', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/mkleina', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'GPG_AGENT_INFO': '/home/mkleina/.gnupg/S.gpg-agent:0:1', 'no_proxy': 'localhost,127.0.0.0/8,::1', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'HTTPS_PROXY': 'http://proxy-mu.intel.com:912/', 'COMPIZ_BIN_PATH': '/usr/bin/', 'QT4_IM_MODULE': 'xim', 'LC_NUMERIC': 'pl_PL.UTF-8', 'HOME': '/home/mkleina', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'LS_COLORS': '', 'XMODIFIERS': '@im=ibus', 'LC_PAPER': 'pl_PL.UTF-8', 'XDG_SESSION_TYPE': 'x11', 'SESSIONTYPE': 'gnome-session', 'XDG_CURRENT_DESKTOP': 'Unity', 'LC_MONETARY': 'pl_PL.UTF-8', 'GOPATH': '/home/mkleina/work', 'SNAP_PATH': '/home/mkleina/work/src/github.com/intelsdi-x/snap', 'XDG_RUNTIME_DIR': '/run/user/1000', 'UPSTART_JOB': 'unity7', 'JOB': 'unity-settings-daemon', 'SESSION': 'ubuntu', 'https_proxy': 'http://proxy-mu.intel.com:912/', 'GDMSESSION': 'ubuntu', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'LOGNAME': 'mkleina', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'SHELL': '/bin/bash', 'INTELSDI_PATH': '/home/mkleina/work/src/github.com/intelsdi-x', 'GIO_LAUNCHED_DESKTOP_FILE': '/usr/share/applications/sublime_text.desktop', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '4798', 'IM_CONFIG_PHASE': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-mHhfCp2NO4', 'XDG_SESSION_ID': 'c2', 'http_proxy': 'http://proxy-mu.intel.com:911/', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'LC_MEASUREMENT': 'pl_PL.UTF-8', 'FTP_PROXY': 'http://proxy-mu.intel.com:911/', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1839', 'XDG_SESSION_DESKTOP': 'ubuntu', 'LANGUAGE': 'en_US', 'ALL_PROXY': 'socks://proxy-mu.intel.com:1080/', 'XDG_VTNR': '7', 'XAUTHORITY': '/home/mkleina/.Xauthority', 'QT_ACCESSIBILITY': '1', 'INSTANCE': '', 'USER': 'mkleina', 'LC_TELEPHONE': 'pl_PL.UTF-8', 'HTTP_PROXY': 'http://proxy-mu.intel.com:911/', 'NO_PROXY': 'localhost,127.0.0.0/8,::1', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'DESKTOP_SESSION': 'ubuntu', 'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'LANG': 'en_US.UTF-8', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'PATH': '/home/mkleina/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/go/bin:/home/mkleina/work/bin:/home/mkleina/kubernetes/cluster/ubuntu/binaries:/home/mkleina/kubernetes/cluster/ubuntu/binaries/master:/home/mkleina/kubernetes/cluster/ubuntu/binaries/minion:/snap/bin:/usr/local/go/bin:/home/mkleina/work/bin:/home/mkleina/kubernetes/cluster/ubuntu/binaries:/home/mkleina/kubernetes/cluster/ubuntu/binaries/master:/home/mkleina/kubernetes/cluster/ubuntu/binaries/minion', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', '_': '/usr/bin/env\n</intelsdi-x/snap-plugin-collector-cgroups/cgroups$ logout', 'DISPLAY': ':0', 'CLUTTER_IM_MODULE': 'xim', 'XDG_SEAT': 'seat0', 'PWD': '/home/mkleina/work/src/github.com/intelsdi-x/snap-plugin-collector-cgroups/cgroups', 'LC_ADDRESS': 'pl_PL.UTF-8', 'ftp_proxy': 'http://proxy-mu.intel.com:911/', 'GDM_LANG': 'en_US', 'GTK_IM_MODULE': 'ibus', 'all_proxy': 'socks://proxy-mu.intel.com:1080/', 'LC_NAME': 'pl_PL.UTF-8', 'GNOME_KEYRING_PID': '', 'QT_IM_MODULE': 'ibus', 'UPSTART_INSTANCE': '', 'GTK2_MODULES': 'overlay-scrollbar', 'KUBERNETES_PROVIDER': 'ubuntu', 'LC_TIME': 'pl_PL.UTF-8', 'GNOME_KEYRING_CONTROL': '', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated'})
GoRename [DEBUG]: ('cmd', 'gorename -offset /home/mkleina/Link to intelsdi-x/snap-plugin-collector-cgroups/cgroups/cgroups.go:#7066 -to getBlablah ')
```

**Comment by mkleina** [comment]
I found the issue - plugin does not support spaces in directories. For example:

GoRename [DEBUG]: ('cmd', 'gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc')

When I try to run this in terminal:
```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc
gorename: surplus arguments
```
As soon as I renamed "my proj" to "my_proj" everything worked great. I never use spaces in directory names, but I was using symlink, which was automatically named "Link to blahblah" and that was the problem.

The gorename tool does not support quotation marks for file path, but it is possible to resolve this by escaping space character. I was able to do this in terminal without any problem:
```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my\ proj/test.go:#682 -to abc
Renamed 2 occurrences in 1 file in 1 package.
```

**Comment by mkleina** [comment]
I found the issue - plugin does not support spaces in directories. For example:
```
GoRename [DEBUG]: ('cmd', 'gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc')
```
When I try to run this in terminal:
```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc
gorename: surplus arguments
```
As soon as I renamed "my proj" to "my_proj" everything worked great. I never use spaces in directory names, but I was using symlink, which was automatically named "Link to blahblah" and that was the problem.

The gorename tool does not support quotation marks for file path, but it is possible to resolve this by escaping space character. I was able to do this in terminal without any problem:
```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my\ proj/test.go:#682 -to abc
Renamed 2 occurrences in 1 file in 1 package.
```

**Comment by mkleina** [comment]
I found the issue - plugin does not support spaces in file path. For example:

```
GoRename [DEBUG]: ('cmd', 'gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc')
```

When I try to run this in terminal:

```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my proj/test.go:#682 -to abc
gorename: surplus arguments
```

As soon as I renamed "my proj" to "my_proj" everything worked great. I never use spaces in directory names, but I was using symlink, which was automatically named "Link to blahblah" and that was the problem.

The gorename tool does not support quotation marks for file path, but it is possible to resolve this by escaping space character. I was able to do this in terminal without any problem:

```
$ gorename -offset /home/mkleina/work/src/github.com/intelsdi-x/my\ proj/test.go:#682 -to abc
Renamed 2 occurrences in 1 file in 1 package.
```

**Comment by alvarolm** [comment]
thanks mkleina !

Any contributions to fix this issue are welcome, currently I don't have the time, somehow the solution should be fairly trivial now that we are aware of the specifics.
https://github.com/alvarolm/GoRename/issues/6
